#!/bin/bash
#
# Script Name: XAMPP (XAMPP Starter)
# Script Author: Ziyaddin Sadigov
# Script URL: http://github.com/ziyaddin/xampp
# Author URL: http://twitter.com/zsadigov
#

FILE="xampp"

if [ -f $FILE ];
then
	echo "\033[32mFile $FILE found.\033[0m"

	#starting main process...
   	while true
		do
			echo -n "Please confirm (y or n) :"
			read CONFIRM

			case $CONFIRM in
			y|Y|YES|yes|Yes)
				
				#copying xampp file to /usr/bin
				sudo cp xampp /usr/bin/xampp
				break
				;;
	
			n|N|no|NO|No)
				echo "\033[31m Aborting\033[0m"
				exit
				;;
	
			*) echo "\033[36m Please enter only y or n!\033[0m"
			esac
		done
	echo "\033[32m Installation of xampp done.\033[0m"

else
   	echo "\033[31mFile $FILE does not exist. Please, try again!\033[0m"
fi

