#!/bin/bash
#
# Script Name: XAMPP (XAMPP Starter)
# Script Author: Ziyaddin Sadigov
# Script URL: http://github.com/ziyaddin/xampp
# Author URL: http://twitter.com/zsadigov
#

# Default commands
DEFAULT_COMMANDS="
  start  startapache  startmysql  startftp
  stop   stopapache   stopmysql   stopftp 
  reload reloadapache reloadmysql reloadftp
  backup restart      security    oci8
  enablessl disablessl"

# Check if arguments entered
if [[ ! -z $1 ]]; then

  # If entered argument are default commands, execute them
  if [[ $DEFAULT_COMMANDS =~ $1 ]]; then
    /opt/lampp/lampp $1

  # For `gui` run xampp-manager with gksu
  # If this command has been started with sudo privileges, open the manager without gksu 
  elif [[ $1 == "gui" ]]; then
    gksu /opt/lampp/manager-linux*.run &

  else
    echo "Unknown command."
  fi

# If arguments aren't entered, output help
else
  echo "
Usage: xampp <command>

  start         Start XAMPP (Apache, MySQL and eventually others)
  startapache   Start only Apache
  startmysql    Start only MySQL
  startftp      Start only ProFTPD

  stop          Stop XAMPP (Apache, MySQL and eventually others)
  stopapache    Stop only Apache
  stopmysql     Stop only MySQL
  stopftp       Stop only ProFTPD

  reload        Reload XAMPP (Apache, MySQL and eventually others)
  reloadapache  Reload only Apache
  reloadmysql   Reload only MySQL
  reloadftp     Reload only ProFTPD

  enablessl     Enable SSL support for Apache
  disablessl    Disable SSL support for Apache

  restart       Stop and start XAMPP
  security      Check XAMPP's security
  backup        Make backup file of your XAMPP config, log and data files
  oci8          Enable the oci8 extenssion

  gui           Graphic interface for XAMPP
"
fi